// Automatische Schema-Migration zur Laufzeit
// Vergleicht aktuelles Datenbankschema mit TypeScript-Interfaces und führt Migrationen durch

export interface Migration {
  type: 'ADD_COLUMN' | 'ALTER_COLUMN' | 'DROP_COLUMN' | 'ADD_TABLE' | 'DROP_TABLE';
  table: string;
  column?: {
    name: string;
    type: string;
    nullable: boolean;
    defaultValue?: any;
    description: string;
  };
  description: string;
}

export interface DatabaseColumn {
  name: string;
  type: string;
  nullable: boolean;
  defaultValue?: any;
  description: string;
}

export interface DatabaseTable {
  name: string;
  columns: DatabaseColumn[];
}

export interface DatabaseSchema {
  tables: DatabaseTable[];
  version?: string;
  hash?: string;
}

export class SchemaMigrationService {
  private currentSchema: DatabaseSchema | null = null;
  private targetSchema: DatabaseSchema | null = null;

  constructor() {
    console.log('🔧 SchemaMigrationService initialisiert');
  }

  /**
   * Lädt das aktuelle Datenbankschema
   */
  async loadCurrentDatabaseSchema(): Promise<DatabaseSchema> {
    try {
      // Hier würde normalerweise eine Datenbank-Abfrage stattfinden
      // Für jetzt simulieren wir ein leeres Schema
      const schema: DatabaseSchema = {
        tables: [],
        version: '0.0.0',
        hash: 'empty'
      };

      console.log('📊 Aktuelles Datenbankschema geladen');
      this.currentSchema = schema;
      return schema;
    } catch (error) {
      console.error('❌ Fehler beim Laden des aktuellen Schemas:', error);
      throw error;
    }
  }

  /**
   * Lädt das Ziel-Schema aus TypeScript-Interfaces
   */
  async loadTargetSchemaFromInterfaces(): Promise<DatabaseSchema> {
    try {
      // Importiere automatisch generierte Schema-Definitionen
      const { AUTO_GENERATED_SCHEMA_DEFINITIONS } = await import('../schemas/generated/autoGeneratedSchema');
      
      // Konvertiere zu DatabaseSchema-Format
      const tables: DatabaseTable[] = Object.values(AUTO_GENERATED_SCHEMA_DEFINITIONS).map(def => ({
        name: def.tableName,
        columns: def.columns.map(col => ({
          name: col.name,
          type: col.type,
          nullable: col.nullable,
          defaultValue: col.defaultValue,
          description: col.description || `${col.name} property`
        }))
      }));

      const schema: DatabaseSchema = {
        tables,
        version: '1.0.0', // Wird aus Build-Info generiert
        hash: 'auto-generated'
      };

      console.log('🎯 Ziel-Schema aus Interfaces geladen');
      this.targetSchema = schema;
      return schema;
    } catch (error) {
      console.error('❌ Fehler beim Laden des Ziel-Schemas:', error);
      throw error;
    }
  }

  /**
   * Generiert Migrations-Skripte basierend auf Schema-Unterschieden
   */
  generateMigrations(currentSchema: DatabaseSchema, targetSchema: DatabaseSchema): Migration[] {
    const migrations: Migration[] = [];
    
    console.log('🔍 Analysiere Schema-Unterschiede...');

    // Finde neue Tabellen
    const currentTableNames = new Set(currentSchema.tables.map(t => t.name));
    const targetTableNames = new Set(targetSchema.tables.map(t => t.name));

    // Neue Tabellen hinzufügen
    targetSchema.tables.forEach(targetTable => {
      if (!currentTableNames.has(targetTable.name)) {
        migrations.push({
          type: 'ADD_TABLE',
          table: targetTable.name,
          description: `Neue Tabelle ${targetTable.name} hinzufügen`
        });

        // Spalten für neue Tabelle hinzufügen
        targetTable.columns.forEach(column => {
          migrations.push({
            type: 'ADD_COLUMN',
            table: targetTable.name,
            column: {
              name: column.name,
              type: column.type,
              nullable: column.nullable,
              defaultValue: column.defaultValue,
              description: column.description || `${column.name} property`
            },
            description: `Spalte ${column.name} zu Tabelle ${targetTable.name} hinzufügen`
          });
        });
      }
    });

    // Bestehende Tabellen analysieren
    currentSchema.tables.forEach(currentTable => {
      const targetTable = targetSchema.tables.find(t => t.name === currentTable.name);
      
      if (targetTable) {
        // Spalten vergleichen
        const currentColumnNames = new Set(currentTable.columns.map(c => c.name));
        const targetColumnNames = new Set(targetTable.columns.map(c => c.name));

        // Neue Spalten hinzufügen
        targetTable.columns.forEach(targetColumn => {
          if (!currentColumnNames.has(targetColumn.name)) {
            migrations.push({
              type: 'ADD_COLUMN',
              table: currentTable.name,
              column: {
                name: targetColumn.name,
                type: targetColumn.type,
                nullable: targetColumn.nullable,
                defaultValue: targetColumn.defaultValue,
                description: targetColumn.description || `${targetColumn.name} property`
              },
              description: `Spalte ${targetColumn.name} zu Tabelle ${currentTable.name} hinzufügen`
            });
          } else {
            // Spalte existiert, prüfe auf Änderungen
            const currentColumn = currentTable.columns.find(c => c.name === targetColumn.name);
            if (currentColumn && this.hasColumnChanged(currentColumn, targetColumn)) {
              migrations.push({
                type: 'ALTER_COLUMN',
                table: currentTable.name,
                column: {
                  name: targetColumn.name,
                  type: targetColumn.type,
                  nullable: targetColumn.nullable,
                  defaultValue: targetColumn.defaultValue,
                  description: targetColumn.description || `${targetColumn.name} property`
                },
                description: `Spalte ${targetColumn.name} in Tabelle ${currentTable.name} ändern`
              });
            }
          }
        });

        // Entfernte Spalten (optional - normalerweise nicht automatisch gelöscht)
        // currentTable.columns.forEach(currentColumn => {
        //   if (!targetColumnNames.has(currentColumn.name)) {
        //     migrations.push({
        //       type: 'DROP_COLUMN',
        //       table: currentTable.name,
        //       column: {
        //         name: currentColumn.name,
        //         type: currentColumn.type,
        //         nullable: currentColumn.nullable,
        //         defaultValue: currentColumn.defaultValue,
        //         description: currentColumn.description
        //       },
        //       description: `Spalte ${currentColumn.name} aus Tabelle ${currentTable.name} entfernen`
        //     });
        //   }
        // });
      }
    });

    // Entfernte Tabellen (optional - normalerweise nicht automatisch gelöscht)
    // currentSchema.tables.forEach(currentTable => {
    //   if (!targetTableNames.has(currentTable.name)) {
    //     migrations.push({
    //       type: 'DROP_TABLE',
    //       table: currentTable.name,
    //       description: `Tabelle ${currentTable.name} entfernen`
    //     });
    //   }
    // });

    console.log(`📋 ${migrations.length} Migrationen generiert`);
    return migrations;
  }

  /**
   * Prüft ob sich eine Spalte geändert hat
   */
  private hasColumnChanged(current: DatabaseColumn, target: DatabaseColumn): boolean {
    return (
      current.type !== target.type ||
      current.nullable !== target.nullable ||
      current.defaultValue !== target.defaultValue
    );
  }

  /**
   * Führt eine Migration aus
   */
  async executeMigration(migration: Migration): Promise<boolean> {
    try {
      console.log(`🔄 Führe Migration aus: ${migration.description}`);

      switch (migration.type) {
        case 'ADD_COLUMN':
          await this.addColumn(migration.table, migration.column!);
          break;
        case 'ALTER_COLUMN':
          await this.alterColumn(migration.table, migration.column!);
          break;
        case 'ADD_TABLE':
          await this.addTable(migration.table);
          break;
        case 'DROP_COLUMN':
          await this.dropColumn(migration.table, migration.column!.name);
          break;
        case 'DROP_TABLE':
          await this.dropTable(migration.table);
          break;
        default:
          console.warn(`⚠️ Unbekannter Migrationstyp: ${migration.type}`);
          return false;
      }

      console.log(`✅ Migration erfolgreich: ${migration.description}`);
      return true;
    } catch (error) {
      console.error(`❌ Migration fehlgeschlagen: ${migration.description}`, error);
      return false;
    }
  }

  /**
   * Fügt eine Spalte zu einer Tabelle hinzu
   */
  private async addColumn(tableName: string, column: DatabaseColumn): Promise<void> {
    // Hier würde normalerweise eine SQL-Ausführung stattfinden
    console.log(`  ➕ Spalte ${column.name} (${column.type}) zu ${tableName} hinzufügen`);
    
    // Simuliere SQL-Ausführung
    const sql = `ALTER TABLE ${tableName} ADD COLUMN ${column.name} ${column.type} ${column.nullable ? '' : 'NOT NULL'}`;
    console.log(`  📝 SQL: ${sql}`);
  }

  /**
   * Ändert eine Spalte in einer Tabelle
   */
  private async alterColumn(tableName: string, column: DatabaseColumn): Promise<void> {
    console.log(`  🔄 Spalte ${column.name} in ${tableName} ändern`);
    
    // Simuliere SQL-Ausführung
    const sql = `ALTER TABLE ${tableName} ALTER COLUMN ${column.name} TYPE ${column.type}`;
    console.log(`  📝 SQL: ${sql}`);
  }

  /**
   * Fügt eine neue Tabelle hinzu
   */
  private async addTable(tableName: string): Promise<void> {
    console.log(`  ➕ Tabelle ${tableName} hinzufügen`);
    
    // Simuliere SQL-Ausführung
    const sql = `CREATE TABLE ${tableName} (id SERIAL PRIMARY KEY)`;
    console.log(`  📝 SQL: ${sql}`);
  }

  /**
   * Entfernt eine Spalte aus einer Tabelle
   */
  private async dropColumn(tableName: string, columnName: string): Promise<void> {
    console.log(`  ➖ Spalte ${columnName} aus ${tableName} entfernen`);
    
    // Simuliere SQL-Ausführung
    const sql = `ALTER TABLE ${tableName} DROP COLUMN ${columnName}`;
    console.log(`  📝 SQL: ${sql}`);
  }

  /**
   * Entfernt eine Tabelle
   */
  private async dropTable(tableName: string): Promise<void> {
    console.log(`  ➖ Tabelle ${tableName} entfernen`);
    
    // Simuliere SQL-Ausführung
    const sql = `DROP TABLE ${tableName}`;
    console.log(`  📝 SQL: ${sql}`);
  }

  /**
   * Hauptfunktion: Prüft und migriert das Schema
   */
  async checkAndMigrate(): Promise<{
    success: boolean;
    migrationsExecuted: number;
    migrationsFailed: number;
    message: string;
  }> {
    try {
      console.log('🚀 Starte Schema-Migration...');

      // Lade aktuelle und Ziel-Schemata
      const currentSchema = await this.loadCurrentDatabaseSchema();
      const targetSchema = await this.loadTargetSchemaFromInterfaces();

      // Generiere Migrationen
      const migrations = this.generateMigrations(currentSchema, targetSchema);

      if (migrations.length === 0) {
        console.log('✅ Schema ist aktuell - keine Migrationen erforderlich');
        return {
          success: true,
          migrationsExecuted: 0,
          migrationsFailed: 0,
          message: 'Schema ist aktuell'
        };
      }

      console.log(`📋 ${migrations.length} Migrationen gefunden`);

      // Führe Migrationen aus
      let executed = 0;
      let failed = 0;

      for (const migration of migrations) {
        const success = await this.executeMigration(migration);
        if (success) {
          executed++;
        } else {
          failed++;
        }
      }

      console.log(`✅ Migration abgeschlossen: ${executed} erfolgreich, ${failed} fehlgeschlagen`);

      return {
        success: failed === 0,
        migrationsExecuted: executed,
        migrationsFailed: failed,
        message: `${executed} Migrationen erfolgreich ausgeführt`
      };

    } catch (error) {
      console.error('❌ Fehler bei Schema-Migration:', error);
      return {
        success: false,
        migrationsExecuted: 0,
        migrationsFailed: 1,
        message: `Fehler: ${error}`
      };
    }
  }

  /**
   * Validiert das aktuelle Schema gegen die Interfaces
   */
  async validateSchema(): Promise<{
    valid: boolean;
    errors: string[];
    warnings: string[];
  }> {
    try {
      const currentSchema = await this.loadCurrentDatabaseSchema();
      const targetSchema = await this.loadTargetSchemaFromInterfaces();
      const migrations = this.generateMigrations(currentSchema, targetSchema);

      const errors: string[] = [];
      const warnings: string[] = [];

      if (migrations.length > 0) {
        warnings.push(`${migrations.length} Schema-Unterschiede gefunden`);
        
        migrations.forEach(migration => {
          if (migration.type === 'ADD_TABLE' || migration.type === 'ADD_COLUMN') {
            warnings.push(`Fehlend: ${migration.description}`);
          }
        });
      }

      return {
        valid: errors.length === 0,
        errors,
        warnings
      };

    } catch (error) {
      return {
        valid: false,
        errors: [`Validierungsfehler: ${error}`],
        warnings: []
      };
    }
  }
}

// Singleton-Instanz
export const schemaMigrationService = new SchemaMigrationService();
